### PR TITLE
add argument option to replace lines with translated content instead …

### PR DESCRIPTION
**Pull request by native2k**
I added an argument option to replace the original line with the translated content.

### CODE REVIEW

**Review by ilyachch — DISMISSED** [review]

**Comment by ilyachch** [comment]
@native2k Thank you for your contribution! I'm really appreciate it!
Please, increase minor version of package. you can do it by calling 
```
$ make bump_minor_release
```
or
```
$ poetry version minor
```

And also, you can check https://github.com/ilyachch/md_docs-trans-app/pull/28 and leave comment if there is something you're lacking for. It would be major version bump release, as the CLI API will be changed. I would be very thankful for your feedback.

**Comment by native2k** [comment]
Hi @ilyachch, bump is done as requested.

**Comment by ilyachch** [comment]
Ok, thank you. I'll check it manually as CI checks are broken now and release it.

**Comment by ilyachch** [comment]
this functions are implemented in version 3, that is just released

**Comment by ilyachch** [comment]
this functions are implemented in version 3, that is just released

**Pull request closed without merging**
